### ISSUE TITLE
Dicionario de Frações em objects.py tem valores float invalidos

### ISSUE THREAD

**Issue by tiagoGuidorizzi** [FernandoFMoreira/TrabalhoGCS#14]
**Comportamento esperado:**

A classe FractionDict deve definir corretamente os tipos de dados para representar um objeto de fração mista. O campo wholeNumber deve ser do tipo `int` para refletir corretamente a parte inteira de uma fração mista.

**Comportamento Atual:**

Atualmente, o campo wholeNumber é definido como **float**, o que é incorreto para representar a parte inteira de uma fração mista. Isso pode levar a confusão e erros ao usar o dicionário para representar frações.

**Ambiente:**
Dicionario

**Descrição detalhada:**

A classe FractionDict está definida da seguinte forma:
```
class FractionDict(TypedDict):
    """Dictionary representing the Fraction object."""

    isNegative: bool
    wholeNumber: float
    numerator: int
```

O campo wholeNumber deveria ser um inteiro (int), pois representa a parte inteira de uma fração mista. A definição correta da classe FractionDict deveria ser:

```
class FractionDict(TypedDict):
    """Dictionary representing the Fraction object."""

    isNegative: bool
    wholeNumber: int
    numerator: int
```

**Possível implementação:**

Alterar o tipo de wholeNumber de float para int na definição da classe FractionDict.

**Comment by Pepenette** [comment]
Estarei finalizando a issue pois corrigi os problemas que existiam:

```
      class FractionDict(TypedDict):
    """Dictionary representing the Fraction object."""

    isNegative: bool
    wholeNumber: int
    numerator: in
```
