### ISSUE TITLE
Dicionario de Frações em objects.py tem operação invalida (divisão por 0)

### ISSUE THREAD

**Issue by tiagoGuidorizzi** [FernandoFMoreira/TrabalhoGCS#15]
**Comportamento esperado:**

A classe FractionDict deve definir corretamente os tipos de dados para representar um objeto de fração. O campo `denominator` deve ser do tipo `int` para refletir corretamente o denominador de uma fração, e deve ser um número inteiro não zero.

**Comportamento Atual:**

Atualmente, o campo denominator é definido como 0, o que não é um tipo de dado válido e não faz sentido, pois o denominador de uma fração não pode ser zero.

**Ambiente:**

Dicionario

**Descrição detalhada:**

A classe FractionDict está definida da seguinte forma:

```pyton
class FractionDict(TypedDict):
    """Dictionary representing the Fraction object."""

    isNegative: bool
    wholeNumber: int
    numerator: int
    denominator: 0 
```

O campo denominator deveria ser um inteiro (int), pois representa o denominador de uma fração. A definição correta da classe FractionDIct deveria ser:

```
class FractionDict(TypedDict):
    """Dictionary representing the Fraction object."""

    isNegative: bool
    wholeNumber: int
    numerator: int
    denominator: int
```

**Possível implementação:**

Alterar o tipo de denominator de 0 para int na definição da classe FractionDict

**Comment by Pepenette** [comment]
Estarei finalizando a issue pois corrigi os problemas que existiam:

```
Negative: bool
wholeNumber: int
numerator: int
denominator: int
```
