### ISSUE TITLE
Tipo de atributos em auth_domain.py configuradas incorretamente

### ISSUE THREAD

**Issue by FernandoFMoreira** [FernandoFMoreira/TrabalhoGCS#20]
**Comportamento esperado:**
Os atributos são capazes de armazenar as informações a respeito das credenciais de autenticação.
```
sub: str
email: str
role: str
```
**Comportamento atual:**
Os atributos armazenam dados de um tipo incompatível com o necessário, e por isso causam erro.
`sub: int
email: int
role: int`
**Ambiente:**
Servidor
**Descrição detalhada**
sub: int
email: int
role: int
Altera o tipo dos atributos em AuthClaimsDict para armazenar dados em formato de inteiro, esse não suportado pela classe AuthClaimsDict.
**Possível implementação**
Alterar o tipo dos atributos de int para str

**Comment by Pepenette** [comment]
Estarei fechando a issue pois implementei e arrumei os erros que possuíam:

```
sub: str
email: str
role: str
```
