### ISSUE TITLE
Regra em tslint.json precisa ser alterada

### ISSUE THREAD

**Issue by FernandoFMoreira** [FernandoFMoreira/TrabalhoGCS#22]
**O que pode ser melhorado:**
A regra `no-useless-files` precisa ser alterada para false.
**O que isso afetaria o projeto no futuro:**
Alteraria a regra sobre arquivos inúteis da CLI, fazendo-a não considerar certos arquivos.
**Como isso pode ser melhorado:**
```
"no-useless-files": false,
```

**Comment by tiagoGuidorizzi** [comment]
Estarei fechando esta issue, pois ja corrigi os erros e implementei as mudanças
