### ISSUE TITLE
Portas em docker-compose.yml configuradas incorretamente

### ISSUE THREAD

**Issue by FernandoFMoreira** [FernandoFMoreira/TrabalhoGCS#23]
**O que vai atrapalhar o projeto no futuro?**
A imagem não pode ser acessada pelo resto da aplicação com configurações anteriores.
```
ports:
   -  "8181:8181"
   -  "8000:8000"
```
**Porque isso aconteceria?**
A configuração das portas abertas por docker-compose.yml está incorreta.
**Como podemos fazer para que isso não continue?**
Alterar as portas em docker-compose.yml para a configuração antiga ou alterar todos os antigos usos das portas da imagem docker para as configurações atualizadas.

**Comment by tiagoGuidorizzi** [comment]
Estarei fechando essa issue, pois os erros ja foram consertados e implementados.
