### ISSUE TITLE
Porta de host do Firebase incorreta em .firabase.json

### ISSUE THREAD

**Issue by tiagoGuidorizzi** [FernandoFMoreira/TrabalhoGCS#5]
**Comportamento Esperado**
A porta comum para o firebase deveria ser 9099

**Comportamentor Atual**
A porta se encontra no host 9090

**Ambiente**
Firebase/Banco de dados

**Descrição detalhada**
Com a porta do firebase no local errado não podemos conectar nossa aplicação ao banco de dados.

**Possivel Implementação**
Retornar ao valor de 9099

**Comment by Pepenette** [comment]
Para corrigir o problema seria necessário alterar a porta do firebase de 9090 para 9099, assim deixando de acordo com a configuração e conectar corretamente o banco de dados

**Comment by FernandoFMoreira** [comment]
Corrigir o problema é simples e de muita importância, vou alterar a porta do firebase para 9099 daqui a pouco
