### ISSUE TITLE
Erro: Cobertura de código em check_overall_backend_test_coverage.py

### ISSUE THREAD

**Issue by Pepenette** [FernandoFMoreira/TrabalhoGCS#6]
**Comportamento esperado:**
O valor para "uncovered_lines" deveria ser -1

**Comportamento Atual:** 
O valor atual é -2

**Ambiente:** 
Back-end

**Descrição detalhada:** 
Ao alterar o valor de "uncovered_lines", mais linhas não vão ser cobertas. Ou seja, a eficiência dos testes vão ser menor.

**Possível implementação:** 
Alterar o valor novamente para 1

**Comment by tiagoGuidorizzi** [comment]
O valor de uncovered_lines em -2 deve ser alterado para que haja uma confiabilidade aceitavel nos testes no backend. Eu proponho que seja criada uma branch "bugFix" para lidar com esse bug e que seja referenciada a issue no Pull Request
