### ISSUE TITLE
Cobertura de código em check_backend_associated_test_file.py

### ISSUE THREAD

**Issue by Pepenette** [FernandoFMoreira/TrabalhoGCS#8]
**Comportamento esperado:**
O comportamento esperado é que o arquivo seja criado e escrito com um conteúdo de exemplo, ocorrendo sem erro, assim permitindo que o teste continue verificando se o arquivo possui um arquivo de teste associado 

**Comportamento Atual:**
Alterando o "w" por "r" em "open(backend_file, 'r', encoding='utf8') as f:" o código tenta abrir o arquivo apenas para a leitura. Se não existir, ocorre uma exceção "FileNotFoundError". Esse teste falha imediatamente pela impossibilidade de abrir um arquivo inexistente para leitura.

**Ambiente:**
Back-end

**Descrição detalhada:**:
A alteração mencionada causa um erro de leitura quando o arquivo não existe ou não pode ser aberto para leitura. Em vez de criar e escrever no arquivo backend_file.py durante o teste, o código tenta apenas ler o conteúdo de um arquivo que não existe, resultando em uma exceção de arquivo não encontrado.

**Possível implementação:**
Alterar da sintaxe "r" por "w"

**Comment by FernandoFMoreira** [comment]
De fato, a correção aqui seria a alteração da sintaxe de leitura "r" por escrita "w"

**Comment by tiagoGuidorizzi** [comment]
Para o bom funcionamento devemos aplicar essa mudança, já que a Issue se configura como blocker e tem prioridade alta. A alteração de sintaxe de "r" para "w" deve ser feita
